title: Page

page: false

fields:
  title:
    label: Title
    type:  title
    
  text:
    label: Text
    type:  textarea

  date:
    icon: calendar
    label: Date
    type: date
    format: LL
    placeholder: Select a date…
    default: today
    required: true
    width: 1/3

  category:
    label: Catégories
    type: tags
    width: 2/3

  tags:
    label: Tags
    type: tags
  seo:
    type: seo


icon: pencil